version: '3'
services:
    webserver:
        image: nginx:latest
        ports:
         - "80:80"
        environment:
         - NGINX_PORT=80
    api:
        build:
          context: ./API
          dockerfile: Dockerfile
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
