version: '3'
services:
    webserver:
        build:
            context: ./NGINX
            dockerfile: Dockerfile
        ports:
         - "80:80"
        environment:
         - NGINX_PORT=80
        container_name: webserver
        hostname: webserver
    api:
        build:
          context: ./API
          dockerfile: Dockerfile
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: root
